version: '3.4'
services:
    web:
        build:
            context : .
            dockerfile: dockerfile
        container_name: covid_19_data_laravel
        depends_on:
            - db
        volumes:
            - ./api:/var/www/html
        env_file: './api/.env'
        environment:
              - "DB_HOST=database"
              - "REDIS_HOST=cache"
              - "DB_HOST=db"
              - "DB_PORT=3306"
              - "DB_DATABASE=zip_db"
              - "DB_USERNAME=devuser"
              - "DB_PASSWORD=devpass"
        ports:
            - 8002:80
    db:
        container_name: lumen_db
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: zip_db
            MYSQL_USER: devuser
            MYSQL_PASSWORD: devpass
        ports: 
            - 6038:3306