version: '3.4'
services:
    api:
        user: www
        build:
            context : ./.docker/api
        container_name: covid_19_data_laravel_fpm
        depends_on:
            - db
            - redis
        volumes:
            - ./api:/var/www/html
        expose:
            - 80
        ports:
            - 8002:80
    db:
        container_name: covid_19_data_laravel_db
        image: mysql:8.0
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment: 
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
        expose:
            - 3306
        ports: 
            - 6038:3306
    redis: 
        container_name: covid_19_data_laravel_redis
        build:
          context: ./.docker/redis
        expose:
          - 6379
        